#pragma once

// h2 debug header start data
#define K_SIMULATION_DEBUG_HEADER_SIGNATURE 'dhsd' 
// h2 debug header end data
#define K_SIMULATION_DEBUG_HEADER_EOF_SIGNATURE 'dhed'
//
#define K_SIMULATION_DEBUG_MAX_GAMESTATES 1
//
#define K_SIMULATION_DEBUG_MAX_UPDATES 5
//
#define K_SIMULATION_DEBUG_GAMESTATE_SAVE_FLAG 0
//
#define K_SIMULATION_DEBUG_GAMESTATE_LOAD_FLAG 0
//
#define K_SIMULATION_DEBUG_GAMESTATE_COMPRESSED_FILE_SIZE 0x40000
//
#define K_SIMULATION_DEBUG_DATA_COMPRESSION_SCRATCH_SIZE 0x4B000
//
#define K_SIMULATION_DEBUG_DATA_DECOMPRESSION_SCRATCH_SIZE 0x10000
//
#define K_SIMULATION_DEBUG_UPDATE_BUFFER_SIZE 0xFFFF

//
#define K_SIMULATION_DEBUG_SAVE_FOLDER_APPEND "\\mods\\debug\\"